### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hzz780** [AElfProject/aelf-web-wallet#1]
## Components

- [x] Fee select [done]  Using Feeselect components under component

- [x] Modal  [done]  Using Pursecipher components under component

## Pages

- [x] Transactions List  [done]   Whether the value of legal tender is displayed remains to be confirmed

- [x] Address Book  [done]

- [x] New Contact Address Page  [done]

- [x] Add Token Page [done]  Transaction list page and token search logic modification

## Internationalization

 - [x] react i18n [done] To be repaired: antd-mobile internationalization

 - [x] Do a representation: How the i18n work. (Code & Logic -> PPT || Blog) [done]  langConfig -> README

**Comment by hzz780** [comment]
## Test & Debug

[TODO]

**Comment by hzz780** [comment]
Test & Debug

https://github.com/AElfProject/aelf-web-wallet/issues/12

https://github.com/AElfProject/aelf-web-wallet/issues/13

https://github.com/AElfProject/aelf-web-wallet/issues/14
