### ISSUE TITLE
【TODO】Token List Page Business Logic Modification and Wallet Existing bug Modification

### ISSUE THREAD

**Issue by bikedawuwang** [AElfProject/aelf-web-wallet#8]
## TokenList
- [x]   TokenList Logic modification [done]
- [x]   Modify existing bugs in wallets []done
- [x]    componentWillReceiveProps -> getDerivedStateFromProps [done]
